server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: jdbc:postgresql://localhost:5432/neto
    username: kenyo
    driver-class-name: org.postgresql.Driver
